# Generated by Django 4.2.14 on 2024-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dose1', models.BooleanField(default=False)),
                ('dose2', models.BooleanField(default=False)),
                ('dose3', models.BooleanField(default=False)),
                ('dose4', models.BooleanField(default=False)),
            ],
        ),
    ]
