# Generated by Django 4.2.14 on 2024-08-09 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dose',
            name='dose1',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='dose2',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='dose3',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='dose4',
        ),
        migrations.AddField(
            model_name='dose',
            name='evening_dose',
            field=models.CharField(choices=[('taken', 'Taken'), ('not_taken', 'Not Taken Yet'), ('missed', 'Missed')], default='not_taken', max_length=20),
        ),
        migrations.AddField(
            model_name='dose',
            name='morning_dose',
            field=models.CharField(choices=[('taken', 'Taken'), ('not_taken', 'Not Taken Yet'), ('missed', 'Missed')], default='not_taken', max_length=20),
        ),
        migrations.AddField(
            model_name='dose',
            name='night_dose',
            field=models.CharField(choices=[('taken', 'Taken'), ('not_taken', 'Not Taken Yet'), ('missed', 'Missed')], default='not_taken', max_length=20),
        ),
        migrations.AddField(
            model_name='dose',
            name='noon_dose',
            field=models.CharField(choices=[('taken', 'Taken'), ('not_taken', 'Not Taken Yet'), ('missed', 'Missed')], default='not_taken', max_length=20),
        ),
        migrations.AddField(
            model_name='dose',
            name='patient',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='tracker.patient'),
            preserve_default=False,
        ),
    ]
