# Generated by Django 4.2.14 on 2024-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_email_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
