# Generated by Django 4.2.14 on 2024-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_userprofile_email_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='profile_photos/'),
        ),
    ]
