# Generated by Django 4.2.14 on 2024-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='tracker/images/default-avatar.png', null=True, upload_to='profile_photos/'),
        ),
    ]
