# Generated by Django 4.2.14 on 2024-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/tracker/images/default-avatar.png', null=True, upload_to='profile_photos/'),
        ),
    ]
